language: python

python:
 - "3.6"
 - "3.6-dev"
 - "3.7-dev"
 - "nightly"
 - "pypy3"

services:
 - redis-server

install:
 - pip install -r requirements.txt -r requirements-test.txt
 - pip install coveralls

before_script:
  - psql -c 'create database mygpo_test;' -U postgres

script:
  - make check-code-format
  - pytest --cov=mygpo/ --cov-branch

after_script:
  - coveralls

env:
 - DATABASE_URL="postgres://postgres@localhost/mygpo_test"

sudo: false

# temporarily allow failures on 3.7
# see https://github.com/chtd/psycopg2cffi/issues/95
matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "nightly"

