
version: '2'

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: contrib/docker.env
    volumes:
      - .:/srv/mygpo
      - ./contrib/docker.env:/docker.env

  postgres:
    build:
      context: contrib
      dockerfile: Dockerfile.postgres

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  web:
    extends: base
    links:
      - redis
      - postgres
      - memcached
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis

  worker:
    extends: base
    command: python manage.py celery worker
    links:
      - web
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  beat:
    extends: base
    command: python manage.py celery beat -S djcelery.schedulers.DatabaseScheduler
    links:
      - web
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
